name: GitHub Actions - Testando Aplicação com com Pytest
run-name: Iniciando testes 
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Usando Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Dependências
        run: |
          python -m pip install --upgrade pip
          pip install \
            pytest==8.4.1 \
            pytest-asyncio==1.1.0 \
            pytest-cov==6.2.1 \
            pydantic==2.11.7 \
            SQLAlchemy==2.0.41

      - name: Rodando teste
        run: |
          echo "iniciando o teste"
          pytest --cov --cov-report=term-missing
